# Rust-based image with cargo-tarpaulin pre-installed
FROM xd009642/tarpaulin 

# This build-arg will be used by cargo-tarpaulin to upload code coverage reports to coveralls
ARG REPO_TOKEN

# Perform apt actions as root
RUN apt install libssl-dev

# Create build directory as root
WORKDIR /usr/src
RUN USER=root cargo new service

# Perform an initial compilation to cache dependencies
WORKDIR /usr/src/service
COPY Cargo.lock Cargo.toml ./
RUN echo "fn main() {println!(\"if you see this, the image build failed and kept the depency-caching entrypoint. check your dockerfile and image build logs.\")}" > src/main.rs
RUN cargo tarpaulin

# Load source code to create final binary
RUN rm -rf src
COPY src src
RUN cargo tarpaulin --coveralls $REPO_TOKEN
